//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploeesOrder
    {
        public int Id { get; set; }
        public byte EmploeesId { get; set; }
        public short OrderId { get; set; }
        public short Done { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Order Order { get; set; }
    }
}
