//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.EmploeesOrder = new HashSet<EmploeesOrder>();
            this.SalaryHistory = new HashSet<SalaryHistory>();
        }
    
        public byte Id { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<byte> WorkingGroup { get; set; }
        public Nullable<byte> Post { get; set; }
    
        public virtual ICollection<EmploeesOrder> EmploeesOrder { get; set; }
        public virtual PostEmploees PostEmploees { get; set; }
        public virtual WorkingGroup WorkingGroup1 { get; set; }
        public virtual ICollection<SalaryHistory> SalaryHistory { get; set; }
    }
}
