//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryMaterials
    {
        public int Id { get; set; }
        public short MaterialId { get; set; }
        public int Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual RawMaterials RawMaterials { get; set; }
    }
}
