//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Order = new HashSet<Order>();
            this.RawMaterialP = new HashSet<RawMaterialP>();
        }
    
        public short Id { get; set; }
        public Nullable<byte> Category { get; set; }
        public string Name { get; set; }
    
        public virtual CatModel CatModel { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<RawMaterialP> RawMaterialP { get; set; }
    }
}
