//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.EmploeesOrder = new HashSet<EmploeesOrder>();
            this.PostOrder = new HashSet<PostOrder>();
        }
    
        public short Id { get; set; }
       
        public Nullable<byte> Costomer { get; set; }
        public string Name { get; set; }
        public byte WorkingGroup { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateOfCompletion { get; set; }
        public Nullable<short> Model { get; set; }
        public string Size { get; set; }
        public short Cost { get; set; }
        public Nullable<int> sum { get; set; }
        public Nullable<int> Done { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<EmploeesOrder> EmploeesOrder { get; set; }
        public virtual Model Model1 { get; set; }
        public virtual WorkingGroup WorkingGroup1 { get; set; }
        public virtual ICollection<PostOrder> PostOrder { get; set; }
    }
}
