//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostEmploees
    {
        public PostEmploees()
        {
            this.Employees = new HashSet<Employees>();
            this.PostOrder = new HashSet<PostOrder>();
        }
    
        public byte Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<PostOrder> PostOrder { get; set; }
    }
}
