//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostOrder
    {
        public PostOrder()
        {
            this.SalaryHistory = new HashSet<SalaryHistory>();
        }
    
        public int Id { get; set; }
        public short OrderId { get; set; }
        public byte PostEmploees { get; set; }
        public double Payment { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PostEmploees PostEmploees1 { get; set; }
        public virtual ICollection<SalaryHistory> SalaryHistory { get; set; }
    }
}
