//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterials
    {
        public RawMaterials()
        {
            this.HistoryMaterials = new HashSet<HistoryMaterials>();
            this.RawMaterialP = new HashSet<RawMaterialP>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Category { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Width { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual CatRawMaterials CatRawMaterials { get; set; }
        public virtual ICollection<HistoryMaterials> HistoryMaterials { get; set; }
        public virtual ICollection<RawMaterialP> RawMaterialP { get; set; }
    }
}
