//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialP
    {
        public byte Id { get; set; }
        public Nullable<short> RawMaterial { get; set; }
        public Nullable<short> Model { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Model Model1 { get; set; }
        public virtual RawMaterials RawMaterials { get; set; }
    }
}
