//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationHistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Translation { get; set; }
        public double Sum { get; set; }
        public Nullable<int> BudgetId { get; set; }
    }
}
